#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: br-build-submit tarball"
    exit 1
fi

if [ ! -f $1 ] ; then
    echo "File $1 does not exist"
    exit 1
fi

curl -H "Expect:" -F uploadedfile=@$1 -F uploadsubmit=1 http://buildroot.humanoidz.org/submit/
